using System;

namespace BLL.DTOs
{
    /// <summary>
    /// Transfer object representing a receipt (comprobante) file attached to a payment or reservation.
    /// </summary>
    /// <remarks>
    /// Either <see cref="PagoID"/> or <see cref="ReservaID"/> must be set to identify the owning entity.
    /// <see cref="Contenido"/> holds the raw file bytes (typically an HTML receipt generated by
    /// <c>ComprobanteGenerator</c>). <see cref="RutaArchivo"/> is an optional filesystem path used
    /// when the file is persisted to disk rather than stored as a BLOB.
    /// <see cref="Id"/> is auto-assigned on construction.
    /// </remarks>
    public class ComprobanteDTO
    {
        /// <summary>Primary key, auto-assigned on construction.</summary>
        public Guid Id { get; set; }
        /// <summary>FK to the associated payment, or <c>null</c> when linked to a reservation instead.</summary>
        public Guid? PagoID { get; set; }
        /// <summary>FK to the associated reservation, or <c>null</c> when linked to a payment instead.</summary>
        public Guid? ReservaID { get; set; }
        /// <summary>Display file name including extension (e.g., <c>"Payment_Receipt_42.html"</c>).</summary>
        public string NombreArchivo { get; set; }
        /// <summary>Optional filesystem path for disk-backed storage. <c>null</c> when content is stored as <see cref="Contenido"/>.</summary>
        public string RutaArchivo { get; set; }
        /// <summary>Timestamp when the receipt was attached. Defaults to <c>DateTime.Now</c> when not set.</summary>
        public DateTime FechaSubida { get; set; }
        /// <summary>Raw file bytes of the receipt document.</summary>
        public byte[] Contenido { get; set; }

        public ComprobanteDTO()
        {
            Id = Guid.NewGuid();
        }
    }
}
