USE [IngSoftwareBase]
GO

-- 1. Insertar Permisos de Cliente en Patente
INSERT INTO Patente (Id, Nombre, TipoAcceso)
VALUES
(NEWID(), 'PERMISSION_CLIENTE_LIST', 'PERMISSION_CLIENTE_LIST'),
(NEWID(), 'PERMISSION_CLIENTE_CREATE', 'PERMISSION_CLIENTE_CREATE'),
(NEWID(), 'PERMISSION_CLIENTE_UPDATE', 'PERMISSION_CLIENTE_UPDATE'),
(NEWID(), 'PERMISSION_CLIENTE_DISABLE', 'PERMISSION_CLIENTE_DISABLE'),
(NEWID(), 'PERMISSION_CLIENTE_CHECKIN', 'PERMISSION_CLIENTE_CHECKIN');
GO

-- 2. Asignar todos los permisos de Cliente al rol 'Administrador'
DECLARE @FamiliaAdminID UNIQUEIDENTIFIER;
SELECT @FamiliaAdminID = Id FROM Familia WHERE Nombre = 'Administrador';

INSERT INTO FamiliaPatente (FamiliaId, PatenteId)
SELECT @FamiliaAdminID, Id
FROM Patente
WHERE Nombre IN (
    'PERMISSION_CLIENTE_LIST',
    'PERMISSION_CLIENTE_CREATE',
    'PERMISSION_CLIENTE_UPDATE',
    'PERMISSION_CLIENTE_DISABLE',
    'PERMISSION_CLIENTE_CHECKIN'
);
GO
