using BLL.DTOs;
using Domain.Entities;
using System;

namespace BLL.Mappers
{
    public static class MembresiaMapper
    {
        public static MembresiaDTO ToDTO(Membresia entity)
        {
            if (entity == null) return null;

            return new MembresiaDTO
            {
                Id = entity.Id,
                Codigo = entity.Codigo,
                Nombre = entity.Nombre,
                Precio = entity.Precio,
                Regularidad = entity.Regularidad,
                Activa = entity.Activa,
                Detalle = entity.Detalle
            };
        }

        public static Membresia ToEntity(MembresiaDTO dto)
        {
            if (dto == null) return null;

            var entity = new Membresia
            {
                Codigo = dto.Codigo,
                Nombre = dto.Nombre,
                Precio = dto.Precio,
                Regularidad = dto.Regularidad,
                Activa = dto.Activa,
                Detalle = dto.Detalle
            };

            // Preserve ID from DTO if it exists (e.g. for updates)
            // Otherwise, keep the new Guid generated by the Membresia constructor
            if (dto.Id != Guid.Empty)
            {
                entity.Id = dto.Id;
            }

            return entity;
        }
    }
}
